export interface WindowsUpgradeScriptInput {
  logFile: string;
  scriptDir: string;
  cleanupPath: string;
  npmCmd: string;
  pkgSpec: string;
  targetVer: string;
  /** Absolute path to daemon-launcher.vbs for hidden restart */
  vbsLauncherPath: string;
  /** Sentinel file — while it exists the watchdog loop pauses */
  upgradeLockFile: string;
}

export function buildWindowsCleanupScript(scriptDir: string): string {
  return `@echo off\r
timeout /t 120 /nobreak >nul\r
rmdir /s /q "${scriptDir}"\r
`;
}

export function buildWindowsUpgradeBatch(input: WindowsUpgradeScriptInput): string {
  const { logFile, cleanupPath, npmCmd, pkgSpec, targetVer, vbsLauncherPath, upgradeLockFile } = input;
  return `@echo off\r
setlocal EnableDelayedExpansion\r
echo === imcodes upgrade started at %date% %time% === >> "${logFile}"\r
timeout /t 2 /nobreak > nul\r
\r
rem ── Create upgrade lock — watchdog will pause while this file exists ──\r
echo upgrade > "${upgradeLockFile}"\r
echo Upgrade lock created >> "${logFile}"\r
\r
rem ── Kill daemon + old watchdog so npm can overwrite files cleanly ─────\r
rem Old watchdog versions don't know about the lock file, so we must kill\r
rem them.  After npm install, repair-watchdog generates a new watchdog\r
rem that respects the lock.\r
set "PIDFILE=%USERPROFILE%\\.imcodes\\daemon.pid"\r
if exist "%PIDFILE%" (\r
  set /p OLD_PID=<"%PIDFILE%"\r
  echo Stopping daemon PID !OLD_PID! and old watchdog... >> "${logFile}"\r
  rem Find watchdog (parent of daemon) and tree-kill it\r
  for /f "tokens=2 delims==" %%a in ('wmic process where "ProcessId=!OLD_PID!" get ParentProcessId /format:list 2^>nul ^| find "="') do (\r
    set "WD_PID=%%a"\r
  )\r
  if defined WD_PID (\r
    taskkill /f /t /pid !WD_PID! >nul 2>&1\r
  )\r
  taskkill /f /pid !OLD_PID! >nul 2>&1\r
  timeout /t 2 /nobreak >nul\r
)\r
\r
echo Installing ${pkgSpec}... >> "${logFile}"\r
call "${npmCmd}" install -g ${pkgSpec} >> "${logFile}" 2>&1\r
if %errorlevel% neq 0 (\r
  echo Install FAILED — removing lock, watchdog will restart current version. >> "${logFile}"\r
  echo === upgrade aborted at %date% %time% === >> "${logFile}"\r
  del "${upgradeLockFile}" >nul 2>&1\r
  if exist "${vbsLauncherPath}" wscript "${vbsLauncherPath}"\r
  start "" /min cmd /c "${cleanupPath}" >nul 2>&1\r
  goto :done\r
)\r
\r
set "NPM_PREFIX="\r
for /f "usebackq delims=" %%p in (\`call "${npmCmd}" prefix -g 2^>nul\`) do if not defined NPM_PREFIX set "NPM_PREFIX=%%p"\r
if not defined NPM_PREFIX (\r
  echo Could not resolve npm global prefix after install. >> "${logFile}"\r
  echo === upgrade aborted at %date% %time% === >> "${logFile}"\r
  del "${upgradeLockFile}" >nul 2>&1\r
  if exist "${vbsLauncherPath}" wscript "${vbsLauncherPath}"\r
  start "" /min cmd /c "${cleanupPath}" >nul 2>&1\r
  goto :done\r
)\r
\r
set "CLI_SHIM=%NPM_PREFIX%\\imcodes.cmd"\r
if not exist "%CLI_SHIM%" (\r
  echo imcodes shim missing after install: %CLI_SHIM% >> "${logFile}"\r
  echo === upgrade aborted at %date% %time% === >> "${logFile}"\r
  del "${upgradeLockFile}" >nul 2>&1\r
  if exist "${vbsLauncherPath}" wscript "${vbsLauncherPath}"\r
  start "" /min cmd /c "${cleanupPath}" >nul 2>&1\r
  goto :done\r
)\r
\r
set "INSTALLED_VER="\r
for /f "usebackq delims=" %%v in (\`call "%CLI_SHIM%" --version 2^>nul\`) do if not defined INSTALLED_VER set "INSTALLED_VER=%%v"\r
echo Install succeeded. Installed version: %INSTALLED_VER%, target: ${targetVer}, shim: %CLI_SHIM% >> "${logFile}"\r
if not "${targetVer}"=="latest" if /I not "%INSTALLED_VER%"=="${targetVer}" (\r
  echo Version mismatch after install — removing lock, watchdog will restart. >> "${logFile}"\r
  echo === upgrade aborted at %date% %time% === >> "${logFile}"\r
  del "${upgradeLockFile}" >nul 2>&1\r
  if exist "${vbsLauncherPath}" wscript "${vbsLauncherPath}"\r
  start "" /min cmd /c "${cleanupPath}" >nul 2>&1\r
  goto :done\r
)\r
where imcodes >nul 2>&1\r
if %errorlevel% neq 0 (\r
  echo WARNING: imcodes not found on PATH >> "${logFile}"\r
  echo To fix: setx PATH "%NPM_PREFIX%;%%PATH%%" >> "${logFile}"\r
)\r
echo Regenerating daemon launch chain... >> "${logFile}"\r
call "%CLI_SHIM%" repair-watchdog >> "${logFile}" 2>&1\r
if %errorlevel% neq 0 (\r
  echo WARNING: Launch chain regeneration failed >> "${logFile}"\r
)\r
\r
rem ── Start new watchdog (lock-aware), then remove lock ─────────────────\r
rem The new watchdog (generated by repair-watchdog) checks the lock file.\r
rem It will loop/wait while the lock exists, then start the daemon once\r
rem we delete it below.\r
echo Starting new watchdog via VBS... >> "${logFile}"\r
if exist "${vbsLauncherPath}" (\r
  wscript "${vbsLauncherPath}"\r
) else (\r
  echo WARNING: VBS launcher not found at ${vbsLauncherPath} >> "${logFile}"\r
)\r
echo Removing upgrade lock... >> "${logFile}"\r
del "${upgradeLockFile}" >nul 2>&1\r
\r
rem Wait for new watchdog to start the daemon, then health-check\r
timeout /t 10 /nobreak >nul\r
if exist "%PIDFILE%" (\r
  set /p DAEMON_PID=<"%PIDFILE%"\r
  tasklist /fi "PID eq !DAEMON_PID!" /nh 2^>nul | find "!DAEMON_PID!" >nul\r
  if !errorlevel! equ 0 (\r
    echo Health check PASSED: daemon PID !DAEMON_PID! alive >> "${logFile}"\r
  ) else (\r
    echo Health check FAILED: PID !DAEMON_PID! not running >> "${logFile}"\r
  )\r
) else (\r
  echo Health check FAILED: daemon.pid not found >> "${logFile}"\r
)\r
start "" /min cmd /c "${cleanupPath}" >nul 2>&1\r
:done\r
echo === upgrade done at %date% %time% === >> "${logFile}"\r
`;
}
